import Footer from '@/components/global/footer';
import ResponsiveNav from '@/components/Home/Navbar/ResponsiveNav';
import { Metadata } from 'next';
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="sticky top-0 z-50 bg-gradient-to-r from-purple-900/80 via-indigo-900/80 to-purple-900/80 backdrop-blur-sm">
        <ResponsiveNav />
      </div>
      <main className="relative z-10">
        {children}
      </main>
      <Footer />
    </>

  );
}