import "@/app/globals.css";
import Footer from '@/components/global/footer';
import { Sidebar, SidebarBody, SidebarProvider } from '@/components/ui/sidebar';
// import { getCurrentUserAction } from "@/lib/actions/currentUser";
// import { Metadata } from "next";
// import { redirect } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const user = await appwriteAuthService.getCurrentUser();

  // if (!user) redirect("/login");
  // const currentUserRes = await getCurrentUserAction();
  // if (currentUserRes.success) {
  //   console.log("Current user: ", currentUserRes.data);
  // } else {
  //   console.log("Error fetching current user: ", currentUserRes.message);
  // }
  return (

    <div className="flex min-h-screen">
      <SidebarProvider>
        <div className="sticky top-0 h-screen flex-shrink-0">
          <Sidebar>
            <SidebarBody>

            </SidebarBody>
          </Sidebar>
        </div>
        <div className="flex-grow flex flex-col">
          {/* <div className="sticky top-0 z-50 bg-gradient-to-r from-purple-900/80 via-indigo-900/80 to-purple-900/80 backdrop-blur-sm">
          </div> */}
          <main className="relative z-10 flex-grow p-5">
            {children}
          </main>
          <Footer />
        </div>
      </SidebarProvider>
    </div>
  );
}