import "@/app/globals.css";
import Footer from '@/components/global/footer';

import { ThemeProvider } from "@/components/theme-provider";
import { Sidebar, SidebarBody, SidebarProvider } from '@/components/ui/sidebar';
import { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
} from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-b from-black via-gray-900 to-black`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >

          <div className="flex min-h-screen">
            <SidebarProvider>
              <div className="sticky top-0 h-screen flex-shrink-0">
              <Sidebar>
              <SidebarBody>
                
              </SidebarBody>
              </Sidebar>
              </div>
           <div className="flex-grow flex flex-col">
          <div className="sticky top-0 z-50 bg-gradient-to-r from-purple-900/80 via-indigo-900/80 to-purple-900/80 backdrop-blur-sm">
            {/* <ResponsiveNav /> */}
            
          </div>
          <main className="relative z-10 flex-grow p-5">
          
            {children}
            
          </main>
          <Footer />
          </div>
          </SidebarProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}